services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - one-proxy-network

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    networks:
      - one-proxy-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - PORT=${PORT}
    networks:
      - one-proxy-network

volumes:
  mongo-data:

networks:
  one-proxy-network: